---
- hosts: hosts
  remote_user: root
  become: yes
  tasks:
  - name: install docker prerequisites
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
  - name: add docker's GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: add docker repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
      state: present
  - name: install docker compose
      get_url: https://github.com/docker/compose/releases/download/1.25.0/docker-compose
      dest: /usr/local/bin/docker-compose
  - name: make it exe
    command: sudo chmod +x /usr/local/bin/docker-compose
  - name: install postgres
    apt:
      name: postgres
      state: present
  - name: install git
    apt:
      name: git
      satate: present